include ./themes/oxocarbon.conf

# Fonts
# BEGIN_KITTY_FONTS
font_family      family="Menlo"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 13.5

# User Interface
hide_window_decorations titlebar-only
window_padding_width 4 8
placement_strategy center

# Keybindings
macos_option_as_alt yes
