# --- Resize Panes ---
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# --- Pane Motions ---
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# --- STATUS BAR ---
set -g status on
set -g status-style bg=black,fg=white   # monochrome base
set -g status-left ""                    # remove left clutter
# set -g status-right "%H:%M"             # just time on right
set -g status-right-length 80
set -g status-right '#[fg=blue]#(pwd="#{pane_current_path}"; echo "${pwd/#$HOME/~}") %I:%M %p'
# set -g status-right '#[fg=blue]#{b:pane_current_path} %I:%M %p'

# --- PANE BORDERS ---
set -g pane-border-style fg=colour238    # inactive borders
set -g pane-active-border-style fg=white # active border highlight
# set -g pane-border-lines heavy            # makes borders feel more visible

# --- OPTIONAL ---
# Remove any status messages
set -g message-style bg=black,fg=white

# --- Preserve Directories across New panes/windows ---
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# --- QOL Improvements ---
set -g history-limit 10000
set -g mouse on
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"  # macOS

# --- Pane Branching and Swqpping ---
bind | split-window -h -c "#{pane_current_path}" # \; select-pane -R
bind - split-window -v -c "#{pane_current_path}" # \; select-pane -D
bind-key < swap-pane -U
bind-key > swap-pane -D
